version = 1
SPDX-PackageName = "kmux"
SPDX-PackageSupplier = "vityas-off <15840124+vityas-off@users.noreply.github.com>"
SPDX-PackageDownloadLocation = "https://github.com/kmux-project/kmux"

[[annotations]]
path = [".gitignore", ".git-blame-ignore-revs", ".krazy", ".editorconfig"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "desktop/kmux.qrc"
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"
