/*
    SPDX-FileCopyrightText: 2026 Kmux contributors

    SPDX-License-Identifier: GPL-2.0-or-later
*/

#include "ProjectIconCatalog.h"

#include <KLocalizedString>

QList<Konsole::ProjectIcon::CatalogEntry> Konsole::ProjectIcon::catalog()
{
    return {
        {QStringLiteral(":/project-icons/material/folder.svg"),
         i18nc("@item:inlistbox project icon", "Folder"),
         QStringLiteral("folder Folder directory files"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/code.svg"),
         i18nc("@item:inlistbox project icon", "Code"),
         QStringLiteral("code Code development programming source"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/terminal.svg"),
         i18nc("@item:inlistbox project icon", "Terminal"),
         QStringLiteral("terminal Terminal shell console command cli"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/dns.svg"),
         i18nc("@item:inlistbox project icon", "Server"),
         QStringLiteral("dns Server hosting backend"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/storage.svg"),
         i18nc("@item:inlistbox project icon", "Database"),
         QStringLiteral("storage Database sql data disk"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/cloud.svg"),
         i18nc("@item:inlistbox project icon", "Cloud"),
         QStringLiteral("cloud Cloud hosting remote"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/public.svg"),
         i18nc("@item:inlistbox project icon", "Web"),
         QStringLiteral("public Web internet globe website browser"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/hub.svg"),
         i18nc("@item:inlistbox project icon", "Network"),
         QStringLiteral("hub Network connections graph"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/widgets.svg"),
         i18nc("@item:inlistbox project icon", "Application"),
         QStringLiteral("widgets Application app software"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/smartphone.svg"),
         i18nc("@item:inlistbox project icon", "Phone"),
         QStringLiteral("smartphone Phone mobile android ios"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/computer.svg"),
         i18nc("@item:inlistbox project icon", "Computer"),
         QStringLiteral("computer Computer desktop pc"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/memory.svg"),
         i18nc("@item:inlistbox project icon", "Hardware"),
         QStringLiteral("memory Hardware cpu chip processor"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/smart_toy.svg"),
         i18nc("@item:inlistbox project icon", "Robot"),
         QStringLiteral("smart toy Robot ai bot artificial intelligence"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/science.svg"),
         i18nc("@item:inlistbox project icon", "Science"),
         QStringLiteral("science Science lab chemistry experiment"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/rocket_launch.svg"),
         i18nc("@item:inlistbox project icon", "Rocket"),
         QStringLiteral("rocket launch Rocket launch deploy space"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/build.svg"),
         i18nc("@item:inlistbox project icon", "Tools"),
         QStringLiteral("build Tools build compile wrench"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/bug_report.svg"),
         i18nc("@item:inlistbox project icon", "Bug"),
         QStringLiteral("bug report Bug debug test issue"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/shield.svg"),
         i18nc("@item:inlistbox project icon", "Shield"),
         QStringLiteral("shield Shield security protection"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/key.svg"),
         i18nc("@item:inlistbox project icon", "Key"),
         QStringLiteral("key Key password authentication"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/lock.svg"),
         i18nc("@item:inlistbox project icon", "Lock"),
         QStringLiteral("lock Lock security private encryption"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/sports_esports.svg"),
         i18nc("@item:inlistbox project icon", "Games"),
         QStringLiteral("sports esports Games gaming controller"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/palette.svg"),
         i18nc("@item:inlistbox project icon", "Art"),
         QStringLiteral("palette Art design colors drawing"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/music_note.svg"),
         i18nc("@item:inlistbox project icon", "Music"),
         QStringLiteral("music note Music audio sound"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/movie.svg"),
         i18nc("@item:inlistbox project icon", "Video"),
         QStringLiteral("movie Video film cinema"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/photo_camera.svg"),
         i18nc("@item:inlistbox project icon", "Camera"),
         QStringLiteral("photo camera Camera photo photography"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/school.svg"),
         i18nc("@item:inlistbox project icon", "Learning"),
         QStringLiteral("school Learning education study"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/book.svg"),
         i18nc("@item:inlistbox project icon", "Book"),
         QStringLiteral("book Book documentation reading"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/home.svg"),
         i18nc("@item:inlistbox project icon", "Home"),
         QStringLiteral("home Home personal house"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/star.svg"),
         i18nc("@item:inlistbox project icon", "Star"),
         QStringLiteral("star Star favorite bookmark"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/favorite.svg"),
         i18nc("@item:inlistbox project icon", "Heart"),
         QStringLiteral("favorite Heart love favorite"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/bolt.svg"),
         i18nc("@item:inlistbox project icon", "Lightning"),
         QStringLiteral("bolt Lightning power energy fast"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/pets.svg"),
         i18nc("@item:inlistbox project icon", "Paw"),
         QStringLiteral("pets Paw animal dog cat"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/folder_open.svg"),
         i18nc("@item:inlistbox project icon", "Open Folder"),
         QStringLiteral("folder open Open Folder directory files"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/folder_shared.svg"),
         i18nc("@item:inlistbox project icon", "Shared Folder"),
         QStringLiteral("folder shared Shared Folder team files"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/snippet_folder.svg"),
         i18nc("@item:inlistbox project icon", "Source Folder"),
         QStringLiteral("snippet folder Source Folder code project files"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/topic.svg"),
         i18nc("@item:inlistbox project icon", "Documents"),
         QStringLiteral("topic Documents folder papers notes"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/inventory_2.svg"),
         i18nc("@item:inlistbox project icon", "Package"),
         QStringLiteral("inventory 2 Package box archive dependency"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/archive.svg"),
         i18nc("@item:inlistbox project icon", "Archive"),
         QStringLiteral("archive Archive backup storage"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/backup.svg"),
         i18nc("@item:inlistbox project icon", "Backup"),
         QStringLiteral("backup Backup restore cloud"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/sync.svg"),
         i18nc("@item:inlistbox project icon", "Sync"),
         QStringLiteral("sync Sync synchronize refresh"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/description.svg"),
         i18nc("@item:inlistbox project icon", "Document"),
         QStringLiteral("description Document source text file"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/integration_instructions.svg"),
         i18nc("@item:inlistbox project icon", "Integration"),
         QStringLiteral("integration instructions Integration api sdk development"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/api.svg"),
         i18nc("@item:inlistbox project icon", "API"),
         QStringLiteral("api API backend endpoint service"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/web.svg"),
         i18nc("@item:inlistbox project icon", "Website"),
         QStringLiteral("web Website frontend browser html"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/language.svg"),
         i18nc("@item:inlistbox project icon", "Languages"),
         QStringLiteral("language Languages translation localization globe"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/html.svg"),
         i18nc("@item:inlistbox project icon", "HTML"),
         QStringLiteral("html HTML markup web frontend"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/css.svg"),
         i18nc("@item:inlistbox project icon", "CSS"),
         QStringLiteral("css CSS style web frontend"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/javascript.svg"),
         i18nc("@item:inlistbox project icon", "JavaScript"),
         QStringLiteral("javascript JavaScript js web programming"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/data_object.svg"),
         i18nc("@item:inlistbox project icon", "JSON"),
         QStringLiteral("data object JSON data object braces"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/data_array.svg"),
         i18nc("@item:inlistbox project icon", "Array"),
         QStringLiteral("data array Array data list brackets"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/schema.svg"),
         i18nc("@item:inlistbox project icon", "Schema"),
         QStringLiteral("schema Schema database diagram"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/account_tree.svg"),
         i18nc("@item:inlistbox project icon", "Branch"),
         QStringLiteral("account tree Branch git tree structure"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/commit.svg"),
         i18nc("@item:inlistbox project icon", "Commit"),
         QStringLiteral("commit Commit git version revision"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/merge.svg"),
         i18nc("@item:inlistbox project icon", "Merge"),
         QStringLiteral("merge Merge git branch combine"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/fork_right.svg"),
         i18nc("@item:inlistbox project icon", "Fork"),
         QStringLiteral("fork right Fork git branch"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/code_blocks.svg"),
         i18nc("@item:inlistbox project icon", "Code Blocks"),
         QStringLiteral("code blocks Code Blocks source snippets"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/extension.svg"),
         i18nc("@item:inlistbox project icon", "Extension"),
         QStringLiteral("extension Extension plugin addon puzzle"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/construction.svg"),
         i18nc("@item:inlistbox project icon", "Construction"),
         QStringLiteral("construction Construction tools work build"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/handyman.svg"),
         i18nc("@item:inlistbox project icon", "Maintenance"),
         QStringLiteral("handyman Maintenance tools repair"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/settings.svg"),
         i18nc("@item:inlistbox project icon", "Settings"),
         QStringLiteral("settings Settings configuration preferences"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/settings_ethernet.svg"),
         i18nc("@item:inlistbox project icon", "Ethernet"),
         QStringLiteral("settings ethernet Ethernet network connection lan"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/router.svg"),
         i18nc("@item:inlistbox project icon", "Router"),
         QStringLiteral("router Router network wifi"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/wifi.svg"),
         i18nc("@item:inlistbox project icon", "Wi-Fi"),
         QStringLiteral("wifi Wi-Fi network wireless internet"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/bluetooth.svg"),
         i18nc("@item:inlistbox project icon", "Bluetooth"),
         QStringLiteral("bluetooth Bluetooth wireless connection"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/lan.svg"),
         i18nc("@item:inlistbox project icon", "Local Network"),
         QStringLiteral("lan Local Network lan infrastructure"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/cable.svg"),
         i18nc("@item:inlistbox project icon", "Cable"),
         QStringLiteral("cable Cable connection wire"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/usb.svg"),
         i18nc("@item:inlistbox project icon", "USB"),
         QStringLiteral("usb USB hardware connection"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/satellite_alt.svg"),
         i18nc("@item:inlistbox project icon", "Satellite"),
         QStringLiteral("satellite alt Satellite space communications"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/cloud_upload.svg"),
         i18nc("@item:inlistbox project icon", "Upload"),
         QStringLiteral("cloud upload Upload cloud deploy publish"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/cloud_download.svg"),
         i18nc("@item:inlistbox project icon", "Download"),
         QStringLiteral("cloud download Download cloud fetch"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/cloud_done.svg"),
         i18nc("@item:inlistbox project icon", "Cloud Ready"),
         QStringLiteral("cloud done Cloud Ready cloud success"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/cloud_queue.svg"),
         i18nc("@item:inlistbox project icon", "Cloud Outline"),
         QStringLiteral("cloud queue Cloud Outline hosting infrastructure"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/folder_zip.svg"),
         i18nc("@item:inlistbox project icon", "ZIP Archive"),
         QStringLiteral("folder zip ZIP Archive compressed files"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/save.svg"),
         i18nc("@item:inlistbox project icon", "Save"),
         QStringLiteral("save Save disk file"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/hard_drive.svg"),
         i18nc("@item:inlistbox project icon", "Hard Drive"),
         QStringLiteral("hard drive Hard Drive disk storage"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/sd_card.svg"),
         i18nc("@item:inlistbox project icon", "Memory Card"),
         QStringLiteral("sd card Memory Card storage sd"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/speed.svg"),
         i18nc("@item:inlistbox project icon", "Speed"),
         QStringLiteral("speed Speed performance benchmark"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/timer.svg"),
         i18nc("@item:inlistbox project icon", "Timer"),
         QStringLiteral("timer Timer time stopwatch benchmark"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/schedule.svg"),
         i18nc("@item:inlistbox project icon", "Clock"),
         QStringLiteral("schedule Clock time schedule"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/calendar_month.svg"),
         i18nc("@item:inlistbox project icon", "Calendar"),
         QStringLiteral("calendar month Calendar date planning"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/check_circle.svg"),
         i18nc("@item:inlistbox project icon", "Check"),
         QStringLiteral("check circle Check success done complete"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/fact_check.svg"),
         i18nc("@item:inlistbox project icon", "Checklist"),
         QStringLiteral("fact check Checklist validation tests tasks"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/rule.svg"),
         i18nc("@item:inlistbox project icon", "Validation"),
         QStringLiteral("rule Validation rules testing"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/verified.svg"),
         i18nc("@item:inlistbox project icon", "Verified"),
         QStringLiteral("verified Verified quality badge certificate"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/monitor_heart.svg"),
         i18nc("@item:inlistbox project icon", "Monitoring"),
         QStringLiteral("monitor heart Monitoring health metrics pulse"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/analytics.svg"),
         i18nc("@item:inlistbox project icon", "Analytics"),
         QStringLiteral("analytics Analytics data metrics chart"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/bar_chart.svg"),
         i18nc("@item:inlistbox project icon", "Bar Chart"),
         QStringLiteral("bar chart Bar Chart statistics data graph"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/pie_chart.svg"),
         i18nc("@item:inlistbox project icon", "Pie Chart"),
         QStringLiteral("pie chart Pie Chart statistics data graph"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/query_stats.svg"),
         i18nc("@item:inlistbox project icon", "Statistics"),
         QStringLiteral("query stats Statistics query metrics graph"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/show_chart.svg"),
         i18nc("@item:inlistbox project icon", "Line Chart"),
         QStringLiteral("show chart Line Chart data trend graph"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/functions.svg"),
         i18nc("@item:inlistbox project icon", "Math"),
         QStringLiteral("functions Math formula function sum"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/calculate.svg"),
         i18nc("@item:inlistbox project icon", "Calculator"),
         QStringLiteral("calculate Calculator math numbers"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/architecture.svg"),
         i18nc("@item:inlistbox project icon", "Architecture"),
         QStringLiteral("architecture Architecture design engineering compass"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/engineering.svg"),
         i18nc("@item:inlistbox project icon", "Engineering"),
         QStringLiteral("engineering Engineering construction design"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/biotech.svg"),
         i18nc("@item:inlistbox project icon", "Biology"),
         QStringLiteral("biotech Biology science research microscope"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/psychology.svg"),
         i18nc("@item:inlistbox project icon", "Intelligence"),
         QStringLiteral("psychology Intelligence brain ai thinking"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/neurology.svg"),
         i18nc("@item:inlistbox project icon", "Neural Network"),
         QStringLiteral("neurology Neural Network brain ai science"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/model_training.svg"),
         i18nc("@item:inlistbox project icon", "Machine Learning"),
         QStringLiteral("model training Machine Learning ai training model"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/precision_manufacturing.svg"),
         i18nc("@item:inlistbox project icon", "Automation"),
         QStringLiteral("precision manufacturing Automation robot industry"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/factory.svg"),
         i18nc("@item:inlistbox project icon", "Factory"),
         QStringLiteral("factory Factory production industry"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/recycling.svg"),
         i18nc("@item:inlistbox project icon", "Recycling"),
         QStringLiteral("recycling Recycling environment reuse"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/energy_savings_leaf.svg"),
         i18nc("@item:inlistbox project icon", "Leaf"),
         QStringLiteral("energy savings leaf Leaf nature environment eco"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/park.svg"),
         i18nc("@item:inlistbox project icon", "Tree"),
         QStringLiteral("park Tree nature forest"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/forest.svg"),
         i18nc("@item:inlistbox project icon", "Forest"),
         QStringLiteral("forest Forest nature trees"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/local_florist.svg"),
         i18nc("@item:inlistbox project icon", "Flower"),
         QStringLiteral("local florist Flower nature garden"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/water_drop.svg"),
         i18nc("@item:inlistbox project icon", "Water"),
         QStringLiteral("water drop Water drop nature"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/local_fire_department.svg"),
         i18nc("@item:inlistbox project icon", "Fire"),
         QStringLiteral("local fire department Fire flame hot"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/wb_sunny.svg"),
         i18nc("@item:inlistbox project icon", "Sun"),
         QStringLiteral("wb sunny Sun weather light day"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/dark_mode.svg"),
         i18nc("@item:inlistbox project icon", "Moon"),
         QStringLiteral("dark mode Moon night dark"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/thunderstorm.svg"),
         i18nc("@item:inlistbox project icon", "Storm"),
         QStringLiteral("thunderstorm Storm weather lightning"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/ac_unit.svg"),
         i18nc("@item:inlistbox project icon", "Snowflake"),
         QStringLiteral("ac unit Snowflake cold winter ice"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/landscape.svg"),
         i18nc("@item:inlistbox project icon", "Landscape"),
         QStringLiteral("landscape Landscape mountain nature"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/hiking.svg"),
         i18nc("@item:inlistbox project icon", "Hiking"),
         QStringLiteral("hiking Hiking map walking mountain"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/travel_explore.svg"),
         i18nc("@item:inlistbox project icon", "Explore"),
         QStringLiteral("travel explore Explore travel web search"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/map.svg"),
         i18nc("@item:inlistbox project icon", "Map"),
         QStringLiteral("map Map location geography"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/explore.svg"),
         i18nc("@item:inlistbox project icon", "Compass"),
         QStringLiteral("explore Compass navigation direction"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/location_on.svg"),
         i18nc("@item:inlistbox project icon", "Location"),
         QStringLiteral("location on Location pin map"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/flight.svg"),
         i18nc("@item:inlistbox project icon", "Airplane"),
         QStringLiteral("flight Airplane travel flight"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/train.svg"),
         i18nc("@item:inlistbox project icon", "Train"),
         QStringLiteral("train Train transport rail"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/directions_car.svg"),
         i18nc("@item:inlistbox project icon", "Car"),
         QStringLiteral("directions car Car transport vehicle"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/directions_bike.svg"),
         i18nc("@item:inlistbox project icon", "Bicycle"),
         QStringLiteral("directions bike Bicycle transport cycling"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/sailing.svg"),
         i18nc("@item:inlistbox project icon", "Sailboat"),
         QStringLiteral("sailing Sailboat travel sea ship"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/work.svg"),
         i18nc("@item:inlistbox project icon", "Work"),
         QStringLiteral("work Work business briefcase"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/apartment.svg"),
         i18nc("@item:inlistbox project icon", "Office"),
         QStringLiteral("apartment Office company building"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/storefront.svg"),
         i18nc("@item:inlistbox project icon", "Shop"),
         QStringLiteral("storefront Shop store commerce"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/shopping_cart.svg"),
         i18nc("@item:inlistbox project icon", "Shopping"),
         QStringLiteral("shopping cart Shopping cart ecommerce"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/payments.svg"),
         i18nc("@item:inlistbox project icon", "Payments"),
         QStringLiteral("payments Payments money finance"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/account_balance.svg"),
         i18nc("@item:inlistbox project icon", "Bank"),
         QStringLiteral("account balance Bank finance institution"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/savings.svg"),
         i18nc("@item:inlistbox project icon", "Savings"),
         QStringLiteral("savings Savings money piggy bank"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/receipt_long.svg"),
         i18nc("@item:inlistbox project icon", "Receipt"),
         QStringLiteral("receipt long Receipt invoice accounting"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/mail.svg"),
         i18nc("@item:inlistbox project icon", "Mail"),
         QStringLiteral("mail Mail email message"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/chat.svg"),
         i18nc("@item:inlistbox project icon", "Chat"),
         QStringLiteral("chat Chat messaging discussion"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/forum.svg"),
         i18nc("@item:inlistbox project icon", "Forum"),
         QStringLiteral("forum Forum community conversation"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/groups.svg"),
         i18nc("@item:inlistbox project icon", "Team"),
         QStringLiteral("groups Team people community"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/person.svg"),
         i18nc("@item:inlistbox project icon", "Person"),
         QStringLiteral("person Person user profile"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/contacts.svg"),
         i18nc("@item:inlistbox project icon", "Contacts"),
         QStringLiteral("contacts Contacts people address book"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/badge.svg"),
         i18nc("@item:inlistbox project icon", "Badge"),
         QStringLiteral("badge Badge identity card"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/campaign.svg"),
         i18nc("@item:inlistbox project icon", "Announcement"),
         QStringLiteral("campaign Announcement marketing megaphone"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/notifications.svg"),
         i18nc("@item:inlistbox project icon", "Bell"),
         QStringLiteral("notifications Bell notification alert"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/rss_feed.svg"),
         i18nc("@item:inlistbox project icon", "RSS"),
         QStringLiteral("rss feed RSS feed news"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/podcasts.svg"),
         i18nc("@item:inlistbox project icon", "Podcast"),
         QStringLiteral("podcasts Podcast audio broadcast"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/headphones.svg"),
         i18nc("@item:inlistbox project icon", "Headphones"),
         QStringLiteral("headphones Headphones audio music"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/mic.svg"),
         i18nc("@item:inlistbox project icon", "Microphone"),
         QStringLiteral("mic Microphone audio recording"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/radio.svg"),
         i18nc("@item:inlistbox project icon", "Radio"),
         QStringLiteral("radio Radio audio broadcast"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/videocam.svg"),
         i18nc("@item:inlistbox project icon", "Video Camera"),
         QStringLiteral("videocam Video Camera recording stream"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/image.svg"),
         i18nc("@item:inlistbox project icon", "Image"),
         QStringLiteral("image Image photo picture"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/brush.svg"),
         i18nc("@item:inlistbox project icon", "Brush"),
         QStringLiteral("brush Brush paint drawing art"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/edit_note.svg"),
         i18nc("@item:inlistbox project icon", "Notes"),
         QStringLiteral("edit note Notes writing editing"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/menu_book.svg"),
         i18nc("@item:inlistbox project icon", "Open Book"),
         QStringLiteral("menu book Open Book documentation manual"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/library_books.svg"),
         i18nc("@item:inlistbox project icon", "Library"),
         QStringLiteral("library books Library books documentation"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/bookmark.svg"),
         i18nc("@item:inlistbox project icon", "Bookmark"),
         QStringLiteral("bookmark Bookmark favorite reading"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/lightbulb.svg"),
         i18nc("@item:inlistbox project icon", "Idea"),
         QStringLiteral("lightbulb Idea light bulb inspiration"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/emoji_objects.svg"),
         i18nc("@item:inlistbox project icon", "Inspiration"),
         QStringLiteral("emoji objects Inspiration idea creativity"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/flag.svg"),
         i18nc("@item:inlistbox project icon", "Flag"),
         QStringLiteral("flag Flag milestone goal"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/track_changes.svg"),
         i18nc("@item:inlistbox project icon", "Target"),
         QStringLiteral("track changes Target goal focus"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/sports_score.svg"),
         i18nc("@item:inlistbox project icon", "Finish"),
         QStringLiteral("sports score Finish flag race milestone"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/sports_soccer.svg"),
         i18nc("@item:inlistbox project icon", "Football"),
         QStringLiteral("sports soccer Football sports soccer"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/fitness_center.svg"),
         i18nc("@item:inlistbox project icon", "Fitness"),
         QStringLiteral("fitness center Fitness sports exercise"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/restaurant.svg"),
         i18nc("@item:inlistbox project icon", "Food"),
         QStringLiteral("restaurant Food cooking meal"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/local_cafe.svg"),
         i18nc("@item:inlistbox project icon", "Coffee"),
         QStringLiteral("local cafe Coffee cafe drink"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/cake.svg"),
         i18nc("@item:inlistbox project icon", "Cake"),
         QStringLiteral("cake Cake birthday celebration"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/celebration.svg"),
         i18nc("@item:inlistbox project icon", "Celebration"),
         QStringLiteral("celebration Celebration party event"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/diamond.svg"),
         i18nc("@item:inlistbox project icon", "Diamond"),
         QStringLiteral("diamond Diamond gem jewelry"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/extension_off.svg"),
         i18nc("@item:inlistbox project icon", "Disabled Plugin"),
         QStringLiteral("extension off Disabled Plugin extension addon"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/vpn_key.svg"),
         i18nc("@item:inlistbox project icon", "Access Key"),
         QStringLiteral("vpn key Access Key vpn authentication security"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/fingerprint.svg"),
         i18nc("@item:inlistbox project icon", "Fingerprint"),
         QStringLiteral("fingerprint Fingerprint identity authentication"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/admin_panel_settings.svg"),
         i18nc("@item:inlistbox project icon", "Administration"),
         QStringLiteral("admin panel settings Administration security management"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/policy.svg"),
         i18nc("@item:inlistbox project icon", "Policy"),
         QStringLiteral("policy Policy security audit"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/visibility.svg"),
         i18nc("@item:inlistbox project icon", "Eye"),
         QStringLiteral("visibility Eye view watch monitor"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/lock_open.svg"),
         i18nc("@item:inlistbox project icon", "Open Lock"),
         QStringLiteral("lock open Open Lock unlock public"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/verified_user.svg"),
         i18nc("@item:inlistbox project icon", "Trusted User"),
         QStringLiteral("verified user Trusted User security verified"),
         Collection::Material},
        {QStringLiteral(":/project-icons/material/password.svg"),
         i18nc("@item:inlistbox project icon", "Password"),
         QStringLiteral("password Password secret authentication"),
         Collection::Material},
        {QStringLiteral(":/project-icons/devicon/c.svg"), QStringLiteral("C"), QStringLiteral("c C language"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/cplusplus.svg"), QStringLiteral("C++"), QStringLiteral("cplusplus C++ language c++ cpp"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/csharp.svg"), QStringLiteral("C#"), QStringLiteral("csharp C# language c#"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/python.svg"),
         QStringLiteral("Python"),
         QStringLiteral("python Python programming language"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/monochrome/rust.svg"),
         QStringLiteral("Rust"),
         QStringLiteral("rust Rust programming language rustlang"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/go.svg"), QStringLiteral("Go"), QStringLiteral("go Go language golang"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/java.svg"), QStringLiteral("Java"), QStringLiteral("java Java programming language jvm"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/kotlin.svg"),
         QStringLiteral("Kotlin"),
         QStringLiteral("kotlin Kotlin language jetbrains jvm kotlinlang"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/swift.svg"), QStringLiteral("Swift"), QStringLiteral("swift Swift language"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/javascript.svg"),
         QStringLiteral("JavaScript"),
         QStringLiteral("javascript JavaScript programming language js ecmascript"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/typescript.svg"),
         QStringLiteral("TypeScript"),
         QStringLiteral("typescript TypeScript programming transpiler javascript language ts"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/ruby.svg"),
         QStringLiteral("Ruby"),
         QStringLiteral("ruby Ruby programming language rubylang"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/php.svg"),
         QStringLiteral("PHP"),
         QStringLiteral("php PHP programming language PHP Hypertext Preprocessor Personal Home Page"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/lua.svg"),
         QStringLiteral("Lua"),
         QStringLiteral("lua Lua programming language object-oriented scripting procedural prototype-based functional lualang"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/perl.svg"), QStringLiteral("Perl"), QStringLiteral("perl Perl programming language"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/r.svg"), QStringLiteral("R"), QStringLiteral("r R programming language rlang"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/julia.svg"),
         QStringLiteral("Julia"),
         QStringLiteral("julia Julia programming language julialang"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/elixir.svg"),
         QStringLiteral("Elixir"),
         QStringLiteral("elixir Elixir language elexirlang"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/erlang.svg"), QStringLiteral("Erlang"), QStringLiteral("erlang Erlang "), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/haskell.svg"),
         QStringLiteral("Haskell"),
         QStringLiteral("haskell Haskell language functional"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/scala.svg"),
         QStringLiteral("Scala"),
         QStringLiteral("scala Scala programming language jvm scalalang"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/clojure.svg"), QStringLiteral("Clojure"), QStringLiteral("clojure Clojure language jvm"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/dart.svg"),
         QStringLiteral("Dart"),
         QStringLiteral("dart Dart programming language googledart"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/zig.svg"), QStringLiteral("Zig"), QStringLiteral("zig Zig language ziglang"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/monochrome/bash.svg"),
         QStringLiteral("Bash"),
         QStringLiteral("bash Bash shell command scripting bourneagainshell"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/powershell.svg"),
         QStringLiteral("PowerShell"),
         QStringLiteral("powershell PowerShell command-line shell terminal cli windows cmdlets ps"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/html5.svg"),
         QStringLiteral("HTML5"),
         QStringLiteral("html5 HTML5 programming language hypertextmarkdownlanguage5"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/css3.svg"),
         QStringLiteral("CSS3"),
         QStringLiteral("css3 CSS3 language programming cascadingstylesheets3"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/sass.svg"), QStringLiteral("Sass"), QStringLiteral("sass Sass pre-processor css scss"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/tailwindcss.svg"),
         QStringLiteral("Tailwind CSS"),
         QStringLiteral("tailwindcss Tailwind CSS css framework"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/bootstrap.svg"),
         QStringLiteral("Bootstrap"),
         QStringLiteral("bootstrap Bootstrap css framework html javascript library"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/react.svg"), QStringLiteral("React"), QStringLiteral("react React framework reactjs"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/vuejs.svg"), QStringLiteral("Vue.js"), QStringLiteral("vuejs Vue.js framework"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/angular.svg"),
         QStringLiteral("Angular"),
         QStringLiteral("angular Angular framework javascript"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/svelte.svg"),
         QStringLiteral("Svelte"),
         QStringLiteral("svelte Svelte javascript framework compiler sveltejs"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/monochrome/nextjs.svg"),
         QStringLiteral("Next.js"),
         QStringLiteral("nextjs Next.js framework"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/nuxtjs.svg"),
         QStringLiteral("Nuxt"),
         QStringLiteral("nuxtjs Nuxt js javascript framework frontend vuejs"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/astro.svg"),
         QStringLiteral("Astro"),
         QStringLiteral("astro Astro static site generator framework web-development"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/nodejs.svg"),
         QStringLiteral("Node.js"),
         QStringLiteral("nodejs Node.js javascript language"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/monochrome/denojs.svg"),
         QStringLiteral("Deno"),
         QStringLiteral("denojs Deno javascript rust runtime"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/bun.svg"), QStringLiteral("Bun"), QStringLiteral("bun Bun javascript zig language"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/monochrome/express.svg"),
         QStringLiteral("Express"),
         QStringLiteral("express Express framework expressjs"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/monochrome/django.svg"), QStringLiteral("Django"), QStringLiteral("django Django "), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/monochrome/flask.svg"),
         QStringLiteral("Flask"),
         QStringLiteral("flask Flask python framework"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/fastapi.svg"),
         QStringLiteral("FastAPI"),
         QStringLiteral("fastapi FastAPI python framework"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/rails.svg"),
         QStringLiteral("Rails"),
         QStringLiteral("rails Rails framework rubyonrails"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/laravel.svg"),
         QStringLiteral("Laravel"),
         QStringLiteral("laravel Laravel php framework"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/spring.svg"),
         QStringLiteral("Spring"),
         QStringLiteral("spring Spring framework springframework"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/dotnetcore.svg"),
         QStringLiteral(".NET"),
         QStringLiteral("dotnetcore .NET framework .netcore"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/flutter.svg"),
         QStringLiteral("Flutter"),
         QStringLiteral("flutter Flutter framework sdk"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/qt.svg"), QStringLiteral("Qt"), QStringLiteral("qt Qt framework"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/electron.svg"),
         QStringLiteral("Electron"),
         QStringLiteral("electron Electron framework electronjs"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/tauri.svg"),
         QStringLiteral("Tauri"),
         QStringLiteral("tauri Tauri nodejs rust desktop framework programming"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/android.svg"), QStringLiteral("Android"), QStringLiteral("android Android os mobile"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/monochrome/apple.svg"),
         QStringLiteral("Apple"),
         QStringLiteral("apple Apple brand mobile"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/linux.svg"), QStringLiteral("Linux"), QStringLiteral("linux Linux os"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/ubuntu.svg"),
         QStringLiteral("Ubuntu"),
         QStringLiteral("ubuntu Ubuntu os open-source linux"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/debian.svg"), QStringLiteral("Debian"), QStringLiteral("debian Debian os server"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/archlinux.svg"),
         QStringLiteral("Arch Linux"),
         QStringLiteral("archlinux Arch Linux linux distribution desktop"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/fedora.svg"),
         QStringLiteral("Fedora"),
         QStringLiteral("fedora Fedora linux distribution desktop"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/nixos.svg"), QStringLiteral("NixOS"), QStringLiteral("nixos NixOS os"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/windows11.svg"), QStringLiteral("Windows"), QStringLiteral("windows11 Windows os"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/raspberrypi.svg"),
         QStringLiteral("Raspberry Pi"),
         QStringLiteral("raspberrypi Raspberry Pi arm computer rpi"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/arduino.svg"),
         QStringLiteral("Arduino"),
         QStringLiteral("arduino Arduino microcontroller hardware"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/docker.svg"), QStringLiteral("Docker"), QStringLiteral("docker Docker platform deploy"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/kubernetes.svg"),
         QStringLiteral("Kubernetes"),
         QStringLiteral("kubernetes Kubernetes container deployment"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/podman.svg"),
         QStringLiteral("Podman"),
         QStringLiteral("podman Podman container pods docker"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/terraform.svg"),
         QStringLiteral("Terraform"),
         QStringLiteral("terraform Terraform deployment architecture automation"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/ansible.svg"),
         QStringLiteral("Ansible"),
         QStringLiteral("ansible Ansible automation provisioning deployment continuous-delivery"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/nginx.svg"), QStringLiteral("NGINX"), QStringLiteral("nginx NGINX server"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/apache.svg"),
         QStringLiteral("Apache"),
         QStringLiteral("apache Apache php The Apache Software Foundation"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/monochrome/amazonwebservices.svg"),
         QStringLiteral("AWS"),
         QStringLiteral("amazonwebservices AWS cloud hosting server aws"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/googlecloud.svg"),
         QStringLiteral("Google Cloud"),
         QStringLiteral("googlecloud Google Cloud google cloud"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/azure.svg"),
         QStringLiteral("Azure"),
         QStringLiteral("azure Azure cloud devops microsoftazure"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/firebase.svg"),
         QStringLiteral("Firebase"),
         QStringLiteral("firebase Firebase auth hosting storage cloud"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/supabase.svg"),
         QStringLiteral("Supabase"),
         QStringLiteral("supabase Supabase authentication cloud-computing-platform database storage"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/postgresql.svg"),
         QStringLiteral("PostgreSQL"),
         QStringLiteral("postgresql PostgreSQL database"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/monochrome/mysql.svg"),
         QStringLiteral("MySQL"),
         QStringLiteral("mysql MySQL database language mystructuredquerylanguage"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/sqlite.svg"), QStringLiteral("SQLite"), QStringLiteral("sqlite SQLite sql database db"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/mongodb.svg"), QStringLiteral("MongoDB"), QStringLiteral("mongodb MongoDB database"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/redis.svg"),
         QStringLiteral("Redis"),
         QStringLiteral("redis Redis server remotedictionaryserver"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/elasticsearch.svg"),
         QStringLiteral("Elasticsearch"),
         QStringLiteral("elasticsearch Elasticsearch elastic data logs"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/git.svg"), QStringLiteral("Git"), QStringLiteral("git Git version-control"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/monochrome/github.svg"),
         QStringLiteral("GitHub"),
         QStringLiteral("github GitHub version-control"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/gitlab.svg"), QStringLiteral("GitLab"), QStringLiteral("gitlab GitLab version-control"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/bitbucket.svg"),
         QStringLiteral("Bitbucket"),
         QStringLiteral("bitbucket Bitbucket version-control atlassianbitbucket"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/cmake.svg"), QStringLiteral("CMake"), QStringLiteral("cmake CMake build"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/monochrome/gradle.svg"),
         QStringLiteral("Gradle"),
         QStringLiteral("gradle Gradle open-source task-runner apachegradle gradlebuildtool"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/npm.svg"),
         QStringLiteral("npm"),
         QStringLiteral("npm npm package manager npmjs nodepackagemanager"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/pnpm.svg"),
         QStringLiteral("pnpm"),
         QStringLiteral("pnpm pnpm package manager performant npm"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/yarn.svg"),
         QStringLiteral("Yarn"),
         QStringLiteral("yarn Yarn package manager javascript js"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/vitejs.svg"),
         QStringLiteral("Vite"),
         QStringLiteral("vitejs Vite javascript build compiler esbuild vite.js Vite"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/webpack.svg"),
         QStringLiteral("Webpack"),
         QStringLiteral("webpack Webpack package manager webpackjs"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/jest.svg"),
         QStringLiteral("Jest"),
         QStringLiteral("jest Jest testing javascript jestjs"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/pytest.svg"),
         QStringLiteral("pytest"),
         QStringLiteral("pytest pytest python framework testing"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/playwright.svg"),
         QStringLiteral("Playwright"),
         QStringLiteral("playwright Playwright testing framework"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/selenium.svg"),
         QStringLiteral("Selenium"),
         QStringLiteral("selenium Selenium webdrive automation"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/pytorch.svg"),
         QStringLiteral("PyTorch"),
         QStringLiteral("pytorch PyTorch programming framework machine-learning python"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/tensorflow.svg"),
         QStringLiteral("TensorFlow"),
         QStringLiteral("tensorflow TensorFlow library machine-learning deep-learning"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/numpy.svg"), QStringLiteral("NumPy"), QStringLiteral("numpy NumPy library python"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/monochrome/pandas.svg"),
         QStringLiteral("pandas"),
         QStringLiteral("pandas pandas library python"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/jupyter.svg"),
         QStringLiteral("Jupyter"),
         QStringLiteral("jupyter Jupyter programming language jupyternotebook"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/opencv.svg"),
         QStringLiteral("OpenCV"),
         QStringLiteral("opencv OpenCV library c/c++ computer-vision"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/godot.svg"),
         QStringLiteral("Godot"),
         QStringLiteral("godot Godot game-engine open-source"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/unity.svg"),
         QStringLiteral("Unity"),
         QStringLiteral("unity Unity C# c-sharp csharp engine game-engine"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/monochrome/unrealengine.svg"),
         QStringLiteral("Unreal Engine"),
         QStringLiteral("unrealengine Unreal Engine c++ engine game-engine"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/blender.svg"),
         QStringLiteral("Blender"),
         QStringLiteral("blender Blender modelling python 3d animation"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/figma.svg"), QStringLiteral("Figma"), QStringLiteral("figma Figma design"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/monochrome/inkscape.svg"),
         QStringLiteral("Inkscape"),
         QStringLiteral("inkscape Inkscape editor vector"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/gimp.svg"), QStringLiteral("GIMP"), QStringLiteral("gimp GIMP graphic"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/vscode.svg"),
         QStringLiteral("VS Code"),
         QStringLiteral("vscode VS Code editor ide visualstudiocode"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/neovim.svg"),
         QStringLiteral("Neovim"),
         QStringLiteral("neovim Neovim text editor editor ide IDE open-source"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/vim.svg"), QStringLiteral("Vim"), QStringLiteral("vim Vim editor viimproved"), Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/intellij.svg"),
         QStringLiteral("IntelliJ IDEA"),
         QStringLiteral("intellij IntelliJ IDEA jetbrains editor java intellijidea"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/prometheus.svg"),
         QStringLiteral("Prometheus"),
         QStringLiteral("prometheus Prometheus monitoring observability analysis"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/grafana.svg"),
         QStringLiteral("Grafana"),
         QStringLiteral("grafana Grafana monitoring analytics metrics logs visualization web-application"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/rabbitmq.svg"),
         QStringLiteral("RabbitMQ"),
         QStringLiteral("rabbitmq RabbitMQ message-broker open-source"),
         Collection::Devicon},
        {QStringLiteral(":/project-icons/devicon/monochrome/apachekafka.svg"),
         QStringLiteral("Kafka"),
         QStringLiteral("apachekafka Kafka streaming open-source"),
         Collection::Devicon},
    };
}
