# SPDX-FileCopyrightText: 2026 Kmux contributors
# SPDX-License-Identifier: BSD-3-Clause

set(git_revision "")
if(GIT_EXECUTABLE)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --short=12 HEAD
        RESULT_VARIABLE git_result
        OUTPUT_VARIABLE git_output
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if(git_result EQUAL 0)
        set(git_revision "${git_output}")
    endif()
endif()

set(header_contents "// Generated by CMake. Do not edit.\n#pragma once\n\n#define KMUX_GIT_REVISION \"${git_revision}\"\n")

set(current_contents "")
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" current_contents)
endif()

if(NOT current_contents STREQUAL header_contents)
    file(WRITE "${OUTPUT_FILE}" "${header_contents}")
endif()
